import { Injectable } from '@angular/core';
import { Observable, map, of } from 'rxjs';
import { ParkingSpace } from '../interfaces/parking-space';

@Injectable({
  providedIn: 'root',
})
export class ParkingPlacesService {
  constructor() {}

  parcari: ParkingSpace[] = [
    {
      id: 0,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 100,
      imageUrl: '../../../assets/images/parking-spaces/parcare3.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 1,
      name: 'Parcare Aeroport',
      owner: 'Jane Smith',
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare2.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: false,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 2,
      name: 'Parcare Subterană',
      owner: 'Alex Johnson',
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 3,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 4,
      name: 'Parcare Aeroport',
      owner: 'Jane Smith',
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare-etaj.jpg',
      isCargoVehicles: true,
      isTruck: false,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date(),
      isFree: true,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 5,
      name: 'Parcare Subterană',
      owner: 'Alex Johnson',
      address: 'Centru oraș',
      locuriDisponibile: 20,
      imageUrl: '../../../assets/images/parking-spaces/parcare5.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 6,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 100,
      imageUrl: '../../../assets/images/parking-spaces/parcare3.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 7,
      name: 'Parcare Aeroport',
      owner: 'Jane Smith',
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare2.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 7,
      name: 'Parcare Subterană',
      owner: 'Alex Johnson',
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 8,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 9,
      name: 'Parcare Subterană',
      owner: 'Alex Johnson',
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 10,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: false,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 11,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 100,
      imageUrl: '../../../assets/images/parking-spaces/parcare3.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 12,
      name: 'Parcare Aeroport',
      owner: 'Jane Smith',
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare2.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: false,
      startDate: new Date(),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 13,
      name: 'Parcare Subterană',
      owner: 'Alex Johnson',
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 14,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: false,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
  ];

  myParkingSpace: ParkingSpace[] = [
    {
      id: 0,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 100,
      imageUrl: '../../../assets/images/parking-spaces/parcare3.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 1,
      name: 'Parcare Aeroport',
      owner: 'Jane Smith',
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare2.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: false,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 2,
      name: 'Parcare Subterană',
      owner: 'Alex Johnson',
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 3,
      name: 'Parcare Centrală',
      owner: 'John Doe',
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
    {
      id: 4,
      name: 'Parcare Aeroport',
      owner: 'Jane Smith',
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare-etaj.jpg',
      isCargoVehicles: true,
      isTruck: false,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date(),
      isFree: true,
      isVideoSurveillance: true,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
    },
  ];

  getParcari(): Observable<ParkingSpace[]> {
    return of(this.parcari);
  }

  getParkingPlaceById(id: any): Observable<any> {
    return this.getParcari().pipe(
      map((values) => {
        return values.find((value) => value.id === id);
      })
    );
  }

  getMyParkingSpace(): Observable<ParkingSpace[]> {
    return of(this.myParkingSpace);
  }
}
