import { Injectable } from '@angular/core';
import { Observable, map, of } from 'rxjs';
import { ParkingSpace } from '../interfaces/parking-space';
import { ParkingSpot } from '../interfaces/parking-spot';
import { ParkingStatus } from '../enums/parking-status';
import { Role } from '../enums/roles';
import { PaymentMethodsMoney } from '../enums/payment-methods';

@Injectable({
  providedIn: 'root',
})
export class ParkingPlacesService {
  constructor() {}

  parkingSpotsMock: ParkingSpot[] = [
    { id: 1, spotNumber: '1A', isReserved: ParkingStatus.AVAILABLE },
    { id: 2, spotNumber: '2A', isReserved: ParkingStatus.OCCUPIED },
    { id: 2, spotNumber: '3A', isReserved: ParkingStatus.PARTIALLYOCCUPIED },
    { id: 4, spotNumber: '4A', isReserved: ParkingStatus.OCCUPIED },
    { id: 5, spotNumber: '5A', isReserved: ParkingStatus.PARTIALLYOCCUPIED },
    { id: 6, spotNumber: '6A', isReserved: ParkingStatus.AVAILABLE },
    { id: 7, spotNumber: '7A', isReserved: ParkingStatus.OCCUPIED },
    { id: 8, spotNumber: '8A', isReserved: ParkingStatus.AVAILABLE },
    { id: 9, spotNumber: '9A', isReserved: ParkingStatus.AVAILABLE },
    { id: 10, spotNumber: '10A', isReserved: ParkingStatus.OCCUPIED },
    { id: 11, spotNumber: '11A', isReserved: ParkingStatus.PARTIALLYOCCUPIED },
    { id: 12, spotNumber: '12A', isReserved: ParkingStatus.PARTIALLYOCCUPIED },
  ];

  parcari: ParkingSpace[] = [
    {
      id: 0,
      name: 'Parcare Centrală',
      owner: {
        id: 0,
        firstname: 'Magda',
        lastname: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 100,
      imageUrl: '../../../assets/images/parking-spaces/parcare3.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      paymentPerHour: PaymentMethodsMoney.PAYMENT_BY_THE_HOUR_MONEY,
      paymentPerDay: PaymentMethodsMoney.PAYMENT_BY_THE_DAY_MONEY,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.        Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces         Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.        Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces         Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces ',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },

    {
      id: 1,
      name: 'Parcare Aeroport',
      owner: {
        id: 0,
        firstname: 'Magda',
        lastname: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        vehicles: [],
      },
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare2.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: false,
      isDraft: true,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },

    {
      id: 2,
      name: 'Parcare Subterană',
      owner: {
        id: 3,
        firstname: 'Andrei',
        lastname: 'Vasilescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user4.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      isDraft: true,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 3,
      name: 'Parcare Centrală',
      owner: {
        id: 4,
        firstname: 'Magda',
        lastname: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'germania',
        isActive: true,
        phone: 2359773,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: false,
        imageUrl: '../../../assets/images/users/user1.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 4,
      name: 'Parcare Aeroport',
      owner: {
        id: 0,
        firstname: 'Magda',
        lastname: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        vehicles: [],
        imageUrl: '../../../assets/images/users/user1.jpg',
      },
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare-etaj.jpg',
      isCargoVehicles: true,
      isTruck: false,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date(),
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      isFree: true,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 5,
      name: 'Parcare Subterană',
      owner: {
        id: 5,
        firstname: 'Ana',
        lastname: 'Dinica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 36659548,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        vehicles: [],
        imageUrl: '../../../assets/images/users/user2.jpg',
      },
      address: 'Centru oraș',
      locuriDisponibile: 20,
      imageUrl: '../../../assets/images/parking-spaces/parcare5.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 6,
      name: 'Parcare Centrală',
      owner: {
        id: 6,
        firstname: 'Dan',
        lastname: 'Ionescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'Romania',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: false,
        imageUrl: '../../../assets/images/users/user3.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 100,
      imageUrl: '../../../assets/images/parking-spaces/parcare3.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 7,
      name: 'Parcare Aeroport',
      owner: {
        id: 7,
        firstname: 'Andrei',
        lastname: 'Vasilescu',
        email: 'magda@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'Franta',
        isActive: true,
        phone: 99568472,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user4.jpg',
        vehicles: [],
      },
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare2.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date(),
      isFree: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      isVideoSurveillance: false,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 7,
      name: 'Parcare Subterană',
      owner: {
        id: 3,
        firstname: 'Andrei',
        lastname: 'Vasilescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user4.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 8,
      name: 'Parcare Centrală',
      owner: {
        id: 3,
        firstname: 'Andrei',
        lastname: 'Vasilescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user4.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 9,
      name: 'Parcare Subterană',
      owner: {
        id: 3,
        firstname: 'Andrei',
        lastname: 'Vasilescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user4.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 10,
      name: 'Parcare Centrală',
      owner: {
        id: 3,
        firstname: 'Andrei',
        lastname: 'Vasilescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user4.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 11,
      name: 'Parcare Centrală',
      owner: {
        id: 3,
        firstname: 'Andrei',
        lastname: 'Vasilescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user4.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 100,
      imageUrl: '../../../assets/images/parking-spaces/parcare3.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date(),
      isFree: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      isVideoSurveillance: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 12,
      name: 'Parcare Aeroport',
      owner: {
        id: 5,
        firstname: 'Ana',
        lastname: 'Dinica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 36659548,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user2.jpg',
        vehicles: [],
      },
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare2.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: false,
      startDate: new Date(),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 13,
      name: 'Parcare Subterană',
      owner: {
        id: 5,
        firstname: 'Ana',
        lastname: 'Dinica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 36659548,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user2.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 14,
      name: 'Parcare Centrală',
      owner: {
        id: 5,
        firstname: 'Ana',
        lastname: 'Dinica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 36659548,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user2.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date('2024-12-31'),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
  ];

  myParkingSpace: ParkingSpace[] = [
    {
      id: 0,
      name: 'Parcare Centrală',
      owner: {
        id: 5,
        firstname: 'Ana',
        lastname: 'Dinica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 36659548,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user2.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 100,
      imageUrl: '../../../assets/images/parking-spaces/parcare3.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      isFree: false,
      isVideoSurveillance: true,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 1,
      name: 'Parcare Aeroport',
      owner: {
        id: 1,
        firstname: 'Ana',
        lastname: 'Dinica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'USA',
        isActive: true,
        phone: 2465863,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user2.jpg',
        vehicles: [],
      },
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare2.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: false,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 2,
      name: 'Parcare Subterană',
      owner: {
        id: 2,
        firstname: 'Dan',
        lastname: 'Ionescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'Belgia',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: false,
        imageUrl: '../../../assets/images/users/user3.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 200,
      imageUrl: '../../../assets/images/parking-spaces/parcare1.jpg',
      isCargoVehicles: true,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date('2024-12-31'),
      isFree: false,
      isVideoSurveillance: true,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 3,
      name: 'Parcare Centrală',
      owner: {
        id: 1,
        firstname: 'Ana',
        lastname: 'Dinica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'USA',
        isActive: true,
        phone: 2465863,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 1234567890123,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user2.jpg',
        vehicles: [],
      },
      address: 'Centru oraș',
      locuriDisponibile: 15,
      imageUrl: '../../../assets/images/parking-spaces/parcare4.jpg',
      isCargoVehicles: false,
      isTruck: true,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date(),
      isFree: false,
      isVideoSurveillance: false,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
    {
      id: 4,
      name: 'Parcare Aeroport',
      owner: {
        id: 0,
        firstname: 'Magda',
        lastname: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        vehicles: [],
      },
      address: 'Aeroport internațional',
      locuriDisponibile: 500,
      imageUrl: '../../../assets/images/parking-spaces/parcare-etaj.jpg',
      isCargoVehicles: true,
      isTruck: false,
      isAgriculturalMachinery: true,
      isPublicTransport: true,
      startDate: new Date(),
      endDate: new Date(),
      isFree: true,
      isVideoSurveillance: true,
      paymentPerHour: 10,
      paymentPerDay: 15,
      paymentForSubscription: 100,
      isDraft: true,
      description:
        'Parking is the act of stopping and disengaging a vehicle and leaving it unoccupied. Parking on one or both sides of a road is often permitted, though sometimes with restrictions. Some buildings have parking facilities for use of the buildings users. Countries and local governments have rules[1] for design and use of parking spaces.',
      parkingSpots: [
        this.parkingSpotsMock[0],
        this.parkingSpotsMock[1],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[2],
        this.parkingSpotsMock[3],
        this.parkingSpotsMock[4],
        this.parkingSpotsMock[5],
        this.parkingSpotsMock[6],
        this.parkingSpotsMock[7],
        this.parkingSpotsMock[8],
        this.parkingSpotsMock[9],
        this.parkingSpotsMock[10],
      ],
    },
  ];

  getParcari(): Observable<ParkingSpace[]> {
    return of(this.parcari);
  }

  getParkingPlaceById(id: any): Observable<any> {
    return this.getParcari().pipe(
      map((values) => {
        return values.find((value) => value.id === id);
      })
    );
  }

  getMyParkingSpace(): Observable<ParkingSpace[]> {
    return of(this.myParkingSpace);
  }
}
