import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { User } from '../interfaces/user';
import { Role } from '../enums/roles';

@Injectable({
  providedIn: 'root',
})
export class UsersService {
  baseUrl: string = 'https://localhost:7010/api/User';

  constructor(private http: HttpClient) {}

  getAllUsers(): Observable<any> {
    return this.http.get<any>(`${this.baseUrl}`);
  }

  users: User[] = [
    {
      id: 0,
      firstname: 'Magda',
      lastname: 'Paicu',
      email: 'john@example.com',
      role: Role.USER,
      address: '123 Main St',
      zipCode: 12345,
      state: 'California',
      isActive: true,
      phone: 1234567890,
      dateOfBirth: new Date('1990-01-01'),
      pnc: 58623332,
      vehiclesRegistered: 'Car, Truck',
      licenseValid: true,
      imageUrl: '../../../assets/images/users/user1.jpg',
      vehicles: [
        {
          imageUrl: '../../../assets/images/vehicles/bmv.jpg',
          make: 'Toyota',
          model: 'Audi',
          color: 'Silver',
          year: 2001,
          ownerId: 0,
          vehicleIdentificationNumber: 1234543789,
        },
        {
          imageUrl: '../../../assets/images/vehicles/bmw2.jpg',
          make: 'kwgffetg',
          model: 'Corolla',
          color: 'Golden',
          year: 1874,
          ownerId: 1,
          vehicleIdentificationNumber: 4253659,
        },
        {
          imageUrl: '../../../assets/images/vehicles/car-default.jpg',
          make: 'jfyuj',
          model: 'BMW',
          color: 'Silver',
          year: 2019,
          ownerId: 2,
          vehicleIdentificationNumber: 123456789,
        },
      ],
    },
    {
      id: 1,
      firstname: 'Ana',
      lastname: 'Dinica',
      email: 'john@example.com',
      role: Role.ADMIN,
      address: '123 Main St',
      zipCode: 12345,
      state: 'USA',
      isActive: true,
      phone: 2465863,
      dateOfBirth: new Date('1990-01-01'),
      pnc: 1234567890123,
      vehiclesRegistered: 'Car, Truck',
      licenseValid: true,
      imageUrl: '../../../assets/images/users/user2.jpg',
      vehicles: [
        {
          imageUrl: '../../../assets/images/vehicles/bmw2.jpg',
          make: 'afdf',
          model: 'Corolla',
          color: 'Red',
          year: 2019,
          ownerId: 3,
          vehicleIdentificationNumber: 123456789,
        },
        {
          imageUrl: '../../../assets/images/vehicles/tractor.jpg',
          make: 'mymngch',
          model: 'ghdkh',
          color: 'White',
          year: 2005,
          ownerId: 4,
          vehicleIdentificationNumber: 123456789,
        },
      ],
    },
    {
      id: 2,
      firstname: 'Dan',
      lastname: 'Ionescu',
      email: 'john@example.com',
      role: Role.USER,
      address: '123 Main St',
      zipCode: 12345,
      state: 'Belgia',
      isActive: true,
      phone: 1234567890,
      dateOfBirth: new Date('1990-01-01'),
      pnc: 1234567890123,
      vehiclesRegistered: 'Car, Truck',
      licenseValid: false,
      imageUrl: '../../../assets/images/users/user3.jpg',
      vehicles: [
        {
          imageUrl: '../../../assets/images/vehicles/bmv.jpg',
          make: 'Toyota',
          model: 'pmbdgc',
          color: 'Silver',
          year: 2019,
          ownerId: 5,
          vehicleIdentificationNumber: 425345,
        },
        {
          imageUrl: '../../../assets/images/vehicles/bmw2.jpg',
          make: 'Toyota',
          model: 'mbfih',
          color: 'Black',
          year: 1996,
          ownerId: 6,
          vehicleIdentificationNumber: 542524,
        },
      ],
    },
    {
      id: 3,
      firstname: 'Andrei',
      lastname: 'Vasilescu',
      email: 'john@example.com',
      role: Role.ADMIN,
      address: '123 Main St',
      zipCode: 12345,
      state: 'California',
      isActive: true,
      phone: 1234567890,
      dateOfBirth: new Date('1990-01-01'),
      pnc: 1234567890123,
      vehiclesRegistered: 'Car, Truck',
      licenseValid: true,
      imageUrl: '../../../assets/images/users/user4.jpg',
      vehicles: [
        {
          imageUrl: '../../../assets/images/vehicles/bmv1.jpg',
          make: 'Toyota',
          model: 'oyrfh',
          color: 'Blue',
          year: 2023,
          ownerId: 7,
          vehicleIdentificationNumber: 96988963,
        },
      ],
    },
    {
      id: 4,
      firstname: 'Magda',
      lastname: 'Paicu',
      email: 'john@example.com',
      role: Role.ADMIN,
      address: '123 Main St',
      zipCode: 12345,
      state: 'germania',
      isActive: true,
      phone: 2359773,
      dateOfBirth: new Date('1990-01-01'),
      pnc: 1234567890123,
      vehiclesRegistered: 'Car, Truck',
      licenseValid: false,
      imageUrl: '../../../assets/images/users/user1.jpg',
      vehicles: [
        {
          imageUrl: '../../../assets/images/vehicles/bmv1.jpg',
          make: 'Toyota',
          model: 'oyrfh',
          color: 'Blue',
          year: 2023,
          ownerId: 7,
          vehicleIdentificationNumber: 96988963,
        },
      ],
    },
    {
      id: 5,
      firstname: 'Ana',
      lastname: 'Dinica',
      email: 'john@example.com',
      role: Role.ADMIN,
      address: '123 Main St',
      zipCode: 12345,
      state: 'California',
      isActive: false,
      phone: 36659548,
      dateOfBirth: new Date('1990-01-01'),
      pnc: 1234567890123,
      vehiclesRegistered: 'Car, Truck',
      licenseValid: true,
      imageUrl: '../../../assets/images/users/user2.jpg',
      vehicles: [
        {
          imageUrl: '../../../assets/images/vehicles/bmv1.jpg',
          make: 'Toyota',
          model: 'oyrfh',
          color: 'Blue',
          year: 2023,
          ownerId: 7,
          vehicleIdentificationNumber: 96988963,
        },
      ],
    },
    {
      id: 6,
      firstname: 'Dan',
      lastname: 'Ionescu',
      email: 'john@example.com',
      role: Role.ADMIN,
      address: '123 Main St',
      zipCode: 12345,
      state: 'Romania',
      isActive: false,
      phone: 1234567890,
      dateOfBirth: new Date('1990-01-01'),
      pnc: 1234567890123,
      vehiclesRegistered: 'Car, Truck',
      licenseValid: false,
      imageUrl: '../../../assets/images/users/user3.jpg',
      vehicles: [
        {
          imageUrl: '../../../assets/images/vehicles/bmv1.jpg',
          make: 'Toyota',
          model: 'oyrfh',
          color: 'Blue',
          year: 2023,
          ownerId: 7,
          vehicleIdentificationNumber: 96988963,
        },
      ],
    },
    {
      id: 7,
      firstname: 'Andrei',
      lastname: 'Vasilescu',
      email: 'magda@example.com',
      role: Role.ADMIN,
      address: '123 Main St',
      zipCode: 12345,
      state: 'Franta',
      isActive: false,
      phone: 99568472,
      dateOfBirth: new Date('1990-01-01'),
      pnc: 1234567890123,
      vehiclesRegistered: 'Car, Truck',
      licenseValid: true,
      imageUrl: '../../../assets/images/users/user4.jpg',
      vehicles: [
        {
          imageUrl: '../../../assets/images/vehicles/bmv1.jpg',
          make: 'Toyota',
          model: 'oyrfh',
          color: 'Blue',
          year: 2023,
          ownerId: 7,
          vehicleIdentificationNumber: 96988963,
        },
      ],
    },
  ];

  getUsers(): Observable<User[]> {
    return of(this.users);
  }
}
