import { Injectable } from '@angular/core';
import { Vehicle } from '../interfaces/vehicle';
import { Observable, of } from 'rxjs';
import { Role } from '../enums/roles';
import { HttpClient } from '@angular/common/http';
import { environment } from 'src/environments/environment.development';

@Injectable({
  providedIn: 'root',
})
export class VehiclesService {
  constructor(private http: HttpClient) {}

  baseUrl: string = environment.apiUrl;

  registerVehicle(newVehicle: any): Observable<Vehicle> {
    return this.http.post<any>(
      `${this.baseUrl}Vehicle/register-vehicle`,
      newVehicle
    );
  }

  getVehicles(): Observable<Vehicle[]> {
    return this.http.get<Vehicle[]>(`${this.baseUrl}Vehicle/vehicles`);
  }

  vehicles: Vehicle[] = [
    {
      vehicleId: 0,
      make: 'Toyota',
      model: 'Audi',
      color: 'Silver',
      year: 2001,
      vehicleOwner: {
        id: 0,
        firstName: 'Magda',
        lastName: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        isVerifiedByAdmin: false,
        dateAdded: new Date('2024-02-11'),
        vehicles: [],
      },
      vehicleIdentificationNumber: 1234543789,
      isVerifiedByAdmin: false,
      dateAdded: new Date('2024-02-11'),
      somethingIsWrong: true,
    },
    {
      vehicleId: 1,
      imageProfileBase64: '../../../assets/images/vehicles/bmw2.jpg',
      make: 'kwgffetg',
      model: 'Corolla',
      color: 'Golden',
      year: 1874,
      vehicleOwner: {
        id: 0,
        firstName: 'Magda',
        lastName: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        isVerifiedByAdmin: false,
        dateAdded: new Date('2024-02-11'),
        vehicles: [],
      },
      vehicleIdentificationNumber: 4253659,
      isVerifiedByAdmin: true,
      dateAdded: new Date('1990-01-01'),
      somethingIsWrong: true,
    },
    {
      vehicleId: 2,
      imageProfileBase64: '../../../assets/images/vehicles/car-default.jpg',
      make: 'jfyuj',
      model: 'BMW',
      color: 'Silver',
      year: 2019,
      vehicleOwner: {
        id: 0,
        firstName: 'george',
        lastName: 'florica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        isVerifiedByAdmin: false,
        dateAdded: new Date('2024-02-11'),
        vehicles: [],
      },
      vehicleIdentificationNumber: 123456789,
      isVerifiedByAdmin: true,
      dateAdded: new Date('1990-01-01'),
      somethingIsWrong: true,
    },
    {
      vehicleId: 3,
      imageProfileBase64: '../../../assets/images/vehicles/bmw2.jpg',
      make: 'afdf',
      model: 'Corolla',
      color: 'Red',
      year: 2019,
      vehicleOwner: {
        id: 0,
        firstName: 'Magda',
        lastName: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        isVerifiedByAdmin: false,
        dateAdded: new Date('2024-02-11'),
        vehicles: [],
      },
      vehicleIdentificationNumber: 123456789,
      isVerifiedByAdmin: false,
      dateAdded: new Date('2024-02-11'),
      somethingIsWrong: false,
    },
    {
      vehicleId: 4,
      imageProfileBase64: '../../../assets/images/vehicles/tractor.jpg',
      make: 'mymngch',
      model: 'ghdkh',
      color: 'White',
      year: 2005,
      vehicleOwner: {
        id: 0,
        firstName: 'Marian',
        lastName: 'Popescu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        isVerifiedByAdmin: false,
        dateAdded: new Date('2024-02-11'),
        vehicles: [],
      },
      vehicleIdentificationNumber: 123456789,
      isVerifiedByAdmin: false,
      dateAdded: new Date('2024-02-11'),
      somethingIsWrong: false,
    },
    {
      vehicleId: 5,
      imageProfileBase64: '../../../assets/images/vehicles/bmv.jpg',
      make: 'Toyota',
      model: 'pmbdgc',
      color: 'Silver',
      year: 2019,
      vehicleOwner: {
        id: 0,
        firstName: 'Magda',
        lastName: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        isVerifiedByAdmin: false,
        dateAdded: new Date('2024-02-11'),
        vehicles: [],
      },
      vehicleIdentificationNumber: 425345,
      isVerifiedByAdmin: false,
      dateAdded: new Date('2024-02-11'),
      somethingIsWrong: true,
    },
    {
      vehicleId: 6,
      imageProfileBase64: '../../../assets/images/vehicles/bmw2.jpg',
      make: 'Toyota',
      model: 'mbfih',
      color: 'Black',
      year: 1996,
      vehicleOwner: {
        id: 0,
        firstName: 'Magda',
        lastName: 'Paicu',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        isVerifiedByAdmin: false,
        dateAdded: new Date('2024-02-11'),
        vehicles: [],
      },
      vehicleIdentificationNumber: 542524,
      isVerifiedByAdmin: true,
      dateAdded: new Date('1990-01-01'),
      somethingIsWrong: false,
    },
    {
      vehicleId: 7,
      imageProfileBase64: '../../../assets/images/vehicles/bmv1.jpg',
      make: 'Toyota',
      model: 'oyrfh',
      color: 'Blue',
      year: 2023,
      vehicleIdentificationNumber: 96988963,
      isVerifiedByAdmin: false,
      dateAdded: new Date('2024-02-11'),
      somethingIsWrong: true,
      vehicleOwner: {
        id: 0,
        firstName: 'Flavius',
        lastName: 'Urzica',
        email: 'john@example.com',
        role: Role.ADMIN,
        address: '123 Main St',
        zipCode: 12345,
        state: 'California',
        isActive: true,
        phone: 1234567890,
        dateOfBirth: new Date('1990-01-01'),
        pnc: 58623332,
        vehiclesRegistered: 'Car, Truck',
        licenseValid: true,
        imageUrl: '../../../assets/images/users/user1.jpg',
        isVerifiedByAdmin: false,
        dateAdded: new Date('2024-02-11'),
        vehicles: [],
      },
    },
  ];

  getAllVehicle(): Observable<Vehicle[]> {
    return of(this.vehicles);
  }
}
