export enum EnumParkingSpacesTable {
  NAME = 'name',
  ADDRESS = 'address',
  AGRICULTURAL_VEHICLES = 'isAgriculturalMachinery',
  PUBLIC_TRANSPORT = 'isPublicTransport',
  CARGO_VEHICLES = 'isCargoVehicles',
  COMPACT_CARDS = 'Compact Cars',
  AVAILABLE_PARKING_SPACES = 'Available Parking Spaces',
  WITH_PAYMENT = 'With Payment',
  VIDEO_SUIVEILLANCE = 'Video Surveillance',
  START_DATE = 'startDate',
  END_DATE = 'endDate',
  AVAILABLE_DAYS = 'Available Days',
  SETTINGS = 'settings',
}
